### ISSUE TITLE
6.0

### ISSUE THREAD

**Issue by stefanpenner** [babel/broccoli-babel-transpiler#62]
placeholder to document what needs to be done ...

**Comment by caridy** [comment]
:pager:

**Comment by maherbeg** [comment]
Are there any updates here? Or any pointers on specific things to look out for? I'd be happy to look into it if I have time next week.

**Comment by stefanpenner** [comment]
@maherbeg upgrading and running the tests following errors is likely the best bet.

Large number of plugins I depend on must be upgraded to make the switch, which makes this not terribly motivating for me. But if others want to take a stab, I wouldn't be apposed.

**Comment by rtablada** [comment]
@stefanpenner any developments?

Right now it looks like not Babel 6 is the big blocker to getting better source maps?

> Large number of plugins I depend on must be upgraded to make the switch, which makes this not terribly motivating for me.

Reving a major version should prevent issues with that in terms of breaking builds and it doesn't look like there has been activity or releases on `master` since November so I'd assume that hindering further dev on this wouldn't be as much of an issue?

**Comment by stefanpenner** [comment]
> Right now it looks like not Babel 6 is the big blocker to getting better source maps?

nope, that isn't a blocker to source-maps.

**Comment by topaxi** [comment]
Which plugins need to be updated exactly? You're talking about some custom Babel 5 plugins, right? :smile:

**Comment by stefanpenner** [comment]
- htmlbars-inline-precompiler
- and several things used in: https://github.com/emberjs/emberjs-build

They at least need to be confirmed to work correctly, or updated if they dont work etc.

**Comment by Turbo87** [comment]
Resolved by #70
