### ISSUE TITLE
cache corruption side channels: plugins needs to be taken into account when deriving cache keys

### ISSUE THREAD

**Issue by stefanpenner** [babel/broccoli-babel-transpiler#67]
1. hashForDep https://github.com/stefanpenner/hash-for-dep of the given plugin (if its an NPM package) this should become part of the plugin subclasses cache key

2. per transform cache key, basically (ideally) the result of options we pass to babel and the babel plugin on each transform. 

Some Side-channel examples: hbs-template-compilter provides a template +  defeaturify step provides features.json

**Comment by stefanpenner** [comment]
Just a note, although logged here (for posterity) this isn't a bug in this repo, rather consuming add-ons must correctly calculate their own cache key. They can do so using many mechanisms, one of which could be using `hash-for-dep` module.

**Comment by stefanpenner** [comment]
This is most likely a mix of:

* documentation
* an example of how some subclasses are not implemented correctly.

**Comment by rwjblue** [comment]
@stefanpenner - I am not sure what you are actually referring to.  What packages subclass this broccoli filter?  Most simply consume it.

Also, broccoli-babel-transpiler is the only thing that is actually aware of the plugins being used.  How would some random package that is simply consuming `broccoli-babel-transpiler` change the babel transpilers internal cache key?

**Comment by stefanpenner** [comment]
Ah the above issue was meant to be opened again the base-class, as it describes things that do not subclass this.

**Comment by dfreeman** [comment]
Talked briefly with @rwjblue about this in Slack — as a concrete example of where this can bite people, templates compiled via `ember-cli-htmlbars-inline-precompile` aren't invalidated when the template compiler changes. This means when running ember-try with config spanning different compilers, some scenarios are doomed to fail.

With [this repo](https://github.com/dfreeman/inline-hbs-caching), which runs a simple integration test against ember-canary and ember-alpha, whichever scenario runs first will pass, and the other will fail due to the compiled template being in an unexpected format.

**Comment by Turbo87** [comment]
@rwjblue can we consider this fixed/implemented now with the latest set of changes?

**Comment by rwjblue** [comment]
I think so. There may still be specific bugs, but I think we can likely close this...
