### ISSUE TITLE
Update to babel-core 6.10.4 to avoid minimatch vulnerability

### ISSUE THREAD

**Issue by jtrees** [babel/broccoli-babel-transpiler#88]
See here:

https://nodesecurity.io/advisories/118

**Comment by Turbo87** [comment]
I'm not sure if this would actually impact us that much since the project is usually only used at build time. The current dependency is set to `^6.0.0` so any bugfix releases like that should get pulled in automatically. Feel free to open a PR to update it but I don't see any immediate need for updating right now. Thanks for reporting this though!
